cmake_minimum_required(VERSION 3.14)
project(uslugi_web LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Threads REQUIRED)
add_library(sqlite_local deps/sqlite3.c)
add_executable(uslugi_web main.cpp)
target_link_libraries(uslugi_web PRIVATE sqlite_local Threads::Threads)
if(WIN32)
    target_link_libraries(uslugi_web PRIVATE winhttp ws2_32)
else()
    find_package(CURL REQUIRED)
    target_link_libraries(uslugi_web PRIVATE CURL::libcurl ${CMAKE_DL_LIBS})
endif()
add_executable(utils_tests tests.cpp)
enable_testing()
add_test(NAME utils COMMAND utils_tests)
